version: '3.8'

# Development override for docker-compose.yml
services:
  backend:
    environment:
      # Enable development features
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_PROFILES_ACTIVE: "docker,dev"
    volumes:
      # Mount source code for hot reload (if needed)
      - ./backend/src:/app/src:ro
      # Mount uploads for development
      - ./backend/uploads:/app/uploads
    ports:
      - "8080:8080"
      - "5005:5005"  # Debug port
    command: ["java", "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005", "-jar", "-Dspring.profiles.active=docker,dev", "target/backend-0.0.1-SNAPSHOT.jar"]

  frontend:
    # For development, you might want to run React dev server instead
    # This would require a different Dockerfile or override
    volumes:
      - ./frontend/src:/app/src:ro
    environment:
      - NODE_ENV=development

  postgres:
    ports:
      - "5432:5432"  # Expose database port for external tools
