version: '3.8'

services:
  # Spring Boot Backend (using host PostgreSQL)
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: eventify-backend
    environment:
      # Database configuration - pointing to host PostgreSQL
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/eventDB
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: karan
      
      # JPA settings
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: true
      
      # File upload settings
      SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE: 10MB
      SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE: 10MB
      
      # Admin contact
      ADMIN_EMAIL: karan.suthar.lakha@gmail.com
      ADMIN_PHONE: +919699073517
      
      # Email configuration
      SPRING_MAIL_HOST: smtp.gmail.com
      SPRING_MAIL_PORT: 587
      SPRING_MAIL_USERNAME: karan.suthar.lakha@gmail.com
      SPRING_MAIL_PASSWORD: ydfn sbdi gkky dtzr
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: true
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: true
      
    ports:
      - "8080:8080"
    volumes:
      - uploads_data:/app/uploads
    networks:
      - eventify-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # React Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: eventify-frontend
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - eventify-network

volumes:
  uploads_data:
    driver: local

networks:
  eventify-network:
    driver: bridge
